### ISSUE TITLE
Is UV_INTENSITY_DARK_SEAWATER_NITRATE a duplicate of UV_INTENSITY_DARK_NITRATE?

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/R03#3]
Whilst looking at the nitrate spec for BGC derivations, I've noticed that we have two nitrate variables that look nearly identical in R03:

UV_INTENSITY_DARK_NITRATE (in nitrate cookbook) defined in R03 as:
Raw ultra-violet (UV) flux signal (count) in darkness from nitrate sensor.

UV_INTENSITY_DARK_SEAWATER_NITRATE (not in nitrate cookbook) defined in R03 as:
Raw ultra-violet (UV) flux signal (count) in seawater and darkness from nitrate sensor.

It seems as though UV_INTENSITY_DARK_SEAWATER_NITRATE might be a duplicate of UV_INTENSITY_DARK_NITRATE.  Is this the case?

**Comment by matdon17** [comment]
I have emailed some of the authors of the nitrate cookbook about this, prior to emailing out through the Argo mailing lists.

**Comment by tlmaurer** [comment]
Hi Matt, UV_INTENSITY_DARK_NITRATE and UV_INTENSITY_SEAWATER_NITRATE are two separate parameters (Dark in DIW versus Dark in Seawater).  UV_INTENSITY_DARK_NITRATE is what is currently used in processing, but we should keep both in the system as acceptable parameters (legacy sensors).

**Comment by catsch** [comment]
thanks tanya.
